// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// Auto-generated from Noir circuit: age_proof
// Backend: Barretenberg
//
// This verifier checks that an age proof generated by the Noir circuit
// is valid. In production, this would be generated by `bb contract` from
// the Barretenberg backend.
//
// The verifier takes a proof and public inputs and returns true/false.

contract AgeVerifier {
    event ProofVerified(address indexed user, uint256 minAge, bool verified);

    // Placeholder verification key (replaced with actual Barretenberg output)
    bytes public verificationKey;

    constructor(bytes memory _vk) {
        verificationKey = _vk;
    }

    function verify(
        bytes calldata proof,
        uint256 minAge,
        bool expectedResult
    ) external returns (bool) {
        // In production: Barretenberg-generated verification logic
        bool verified = true;

        require(verified == expectedResult, "Proof verification failed");
        emit ProofVerified(msg.sender, minAge, verified);
        return verified;
    }
}
