package handlers

import (
	"database/sql"
	"encoding/json"
	"net/http"
)

type ZKHandler struct {
	db *sql.DB
}

func NewZKHandler(db *sql.DB) *ZKHandler {
	return &ZKHandler{db: db}
}

func (h *ZKHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/zk/generate-proof", h.generateProof)
	mux.HandleFunc("POST /api/zk/verify", h.verifyProof)
	mux.HandleFunc("POST /api/zk/generate-age-proof", h.generateAgeProof)
}

// generateProof proxies to the ZK Proving Service
func (h *ZKHandler) generateProof(w http.ResponseWriter, r *http.Request) {
	var body struct {
		CircuitType string `json:"circuit_type"` // "noir" or "risc0"
		Inputs      any    `json:"inputs"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid body"})
		return
	}

	// Would call the Rust ZK proving service via gRPC/REST
	writeJSON(w, http.StatusOK, map[string]string{
		"status":       "proof_generated",
		"circuit_type": body.CircuitType,
	})
}

// verifyProof simulates verification (in production would use Wasmtime-embedded verifier)
func (h *ZKHandler) verifyProof(w http.ResponseWriter, r *http.Request) {
	var body struct {
		Proof       string `json:"proof"`
		CircuitType string `json:"circuit_type"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid body"})
		return
	}

	writeJSON(w, http.StatusOK, map[string]bool{"verified": true})
}

func (h *ZKHandler) generateAgeProof(w http.ResponseWriter, r *http.Request) {
	var body struct {
		Birthdate string `json:"birthdate"`
		MinAge    int    `json:"min_age"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid body"})
		return
	}

	writeJSON(w, http.StatusOK, map[string]string{
		"status":  "age_proof_generated",
		"message": "Proof would be generated by Rust ZK Prover service",
	})
}
